language: php

sudo: false

php:
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - if [[ $(phpenv version-name) == '7.1' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
  - if [[ $(phpenv version-name) != '7.1' ]]; then composer install -n ; fi

script:
  - if [[ $(phpenv version-name) == '7.1' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $(phpenv version-name) != '7.1' ]]; then vendor/bin/phpunit ; fi

after_script:
  - if [[ $(phpenv version-name) == '7.1' ]]; then php vendor/bin/coveralls -v ; fi